### ISSUE TITLE
SEWebView crash when click on textfield

### ISSUE THREAD

**Issue by moneymour** [saltedge/saltedge-ios#95]
Hello, 

i added 'SaltEdge-iOS', '~> 4.0' in my swift project, when try to click on textfield for search provider my app crash with this error:

API error: <_UIKBCompatInputView: 0x7f9e0a5b0f30; frame = (0 0; 0 0); layer = <CALayer: 0x600000037160>> returned 0 width, assuming UIViewNoIntrinsicMetric
2018-02-12 22:54:42.872193+0100 Moneymour[79026:2435575] API error: 

<_UIKBCompatInputView: 0x7f9e0a5b0f30; frame = (0 0; 0 0); layer = <CALayer: 0x600000037160>> returned 0 width, assuming UIViewNoIntrinsicMetric
2018-02-12 22:54:42.933815+0100 Moneymour[79026:2435575] -[UILayoutGuide flk_nameTag]: unrecognized selector sent to instance 0x6040001b3160
2018-02-12 22:54:42.979824+0100 Moneymour[79026:2435575] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UILayoutGuide flk_nameTag]: unrecognized selector sent to instance 0x6040001b3160'

we can help me ?

**Comment by idanci** [comment]
Hi, forwarded to our iOS devs, @nemesis will update you with more details soon.

**Comment by nemesis** [comment]
Hi @moneymour, as you can see by the trace, the issue is in one of the libraries your app uses. Specifically, `flk_nameTag` (which is not part of the iOS SDK) causes the crash. May it be so that [FLKAutoLayout](https://github.com/floriankugler/FLKAutoLayout) wasn't loaded in the runtime when this method got called? 

It would be better if you'd provide a sample Xcode project or a controller gist (https://gist.github.com/) which reproduces the bug, but even then, it's out of the scope of the SDK. 

You should create an issue in the layout library's [issue tracker](https://github.com/floriankugler/FLKAutoLayout/issues) and ask for help there. `SEWebView` is just a wrapper around `UIWebView` for handling URL callbacks and does not contain any layout logic at all, that's up to the consumer.
